# Generated by Django 5.2.12 on 2026-04-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_user_phone_number'),
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWealthRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='关联ID')),
                ('wealth_amount', models.DecimalField(db_column='wealth_amount', decimal_places=2, default=0, max_digits=18, verbose_name='货币数量')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wealth_relations', to='user.user', verbose_name='用户')),
                ('wealth', models.ForeignKey(db_column='wealth_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='wealth.wealth', verbose_name='货币资产')),
            ],
            options={
                'verbose_name': '用户货币资产关联',
                'verbose_name_plural': '用户货币资产关联',
                'db_table': 'user_wealth_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'wealth'), name='uniq_user_wealth')],
            },
        ),
    ]
