# Generated by Django 5.2.12 on 2026-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wealth',
            fields=[
                ('wealth_id', models.AutoField(db_column='wealth_id', primary_key=True, serialize=False, verbose_name='货币资产ID')),
                ('wealth_name', models.CharField(db_column='wealth_name', max_length=100, unique=True, verbose_name='货币资产名称')),
            ],
            options={
                'verbose_name': '货币资产',
                'verbose_name_plural': '货币资产',
                'db_table': 'wealth',
            },
        ),
    ]
