# Generated by Django 5.2.12 on 2026-04-18 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPropertyRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='关联ID')),
                ('property_amount', models.IntegerField(db_column='property_amount', default=0, verbose_name='属性数值')),
                ('property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='property.property', verbose_name='属性')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='property_relations', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户属性关联',
                'verbose_name_plural': '用户属性关联',
                'db_table': 'user_property_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'property'), name='uniq_user_property')],
            },
        ),
    ]
