# Generated by Django 5.2.12 on 2026-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(db_column='achievement_id', primary_key=True, serialize=False, verbose_name='成就ID')),
                ('achievement_name', models.CharField(db_column='achievement_name', max_length=100, unique=True, verbose_name='成就名称')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'db_table': 'achievement',
            },
        ),
    ]
