# Generated by Django 5.2.12 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('pet_model_id', models.AutoField(db_column='pet_model_id', primary_key=True, serialize=False, verbose_name='模型ID')),
                ('pet_model_name', models.CharField(max_length=200, verbose_name='模型名称')),
            ],
            options={
                'verbose_name': '宠物模型',
                'verbose_name_plural': '宠物模型',
                'db_table': 'pet_model',
            },
        ),
    ]
