# Generated by Django 5.2.12 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetAction',
            fields=[
                ('pet_action_id', models.AutoField(db_column='pet_action_id', primary_key=True, serialize=False, verbose_name='动作ID')),
                ('pet_action_name', models.CharField(max_length=200, verbose_name='动作名称')),
            ],
            options={
                'verbose_name': '动作',
                'verbose_name_plural': '动作',
                'db_table': 'pet_action',
            },
        ),
    ]
