# Generated by Django 5.2.12 on 2026-04-18 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievement', '0001_initial'),
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievementRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='关联ID')),
                ('achievement', models.ForeignKey(db_column='achievement_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='achievement.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievement_relations', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就关联',
                'verbose_name_plural': '用户成就关联',
                'db_table': 'user_achievement_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='uniq_user_achievement')],
            },
        ),
    ]
