# Generated by Django 5.2.12 on 2026-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(db_column='property_id', primary_key=True, serialize=False, verbose_name='属性ID')),
                ('property_name', models.CharField(db_column='property_name', max_length=100, unique=True, verbose_name='属性名称')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
                'db_table': 'property',
            },
        ),
    ]
