# Generated by Django 5.2.12 on 2026-04-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furniture', '0001_initial'),
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFurnitureRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='关联ID')),
                ('furniture_amount', models.IntegerField(db_column='furniture_amount', default=0, verbose_name='家具数量')),
                ('furniture', models.ForeignKey(db_column='furniture_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='furniture.furniture', verbose_name='家具')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='furniture_relations', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户家具关联',
                'verbose_name_plural': '用户家具关联',
                'db_table': 'user_furniture_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'furniture'), name='uniq_user_furniture')],
            },
        ),
    ]
