# Generated by Django 5.2.12 on 2026-04-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('user_task_id', models.AutoField(db_column='user_task_id', primary_key=True, serialize=False, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户任务',
                'verbose_name_plural': '用户任务',
                'db_table': 'user_task',
            },
        ),
    ]
