# Generated by Django 5.2.12 on 2026-04-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_model', '0001_initial'),
        ('user', '0002_alter_user_user_mail_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('user_task_id', models.AutoField(db_column='user_task_id', primary_key=True, serialize=False, verbose_name='模型ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('model_address', models.CharField(max_length=500, verbose_name='模型地址')),
                ('pet_model', models.ForeignKey(db_column='pet_model_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='pet_model.petmodel', verbose_name='宠物模型')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '宠物模型',
                'verbose_name_plural': '宠物模型',
                'db_table': 'user_task',
            },
        ),
    ]
