# Generated by Django 5.2.12 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_phone_number'),
        ('user_task', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('user', 'task_name'), name='uniq_user_task_name'),
        ),
    ]
