# Generated by Django 5.2.12 on 2026-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0002_usertask_uniq_user_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='meshy_job_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Meshy任务ID'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='meshy_retry_count',
            field=models.IntegerField(default=0, verbose_name='Meshy重试次数'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='pet_breed',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='宠物品种'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='pet_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='宠物类型'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='texture_clean_path',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='贴图路径'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='workflow_error',
            field=models.TextField(blank=True, default='', verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='workflow_status',
            field=models.CharField(choices=[('pending', '待开始'), ('cleaned', '图片已预处理'), ('meshy_pending', 'Meshy 任务已提交'), ('IN_PROGRESS', 'Meshy 生成中'), ('PENDING', 'Meshy 排队中'), ('resubmit_pending', '重试提交中'), ('meshy_done', 'Meshy 完成'), ('TEXTURE_PROCESSING', '贴图处理中'), ('DONE', '全部完成'), ('FAILED', 'Meshy 失败'), ('ERROR', '本地错误')], default='pending', max_length=32, verbose_name='工作流状态'),
        ),
    ]
