# Generated by Django 5.2.12 on 2026-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0004_uuid_pk_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='pet_model_id',
            field=models.IntegerField(default=0, verbose_name='宠物模型ID'),
        ),
    ]
