# Generated by Django 5.2.12 on 2026-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('furniture_id', models.AutoField(db_column='furniture_id', primary_key=True, serialize=False, verbose_name='家具ID')),
                ('furniture_name', models.CharField(db_column='furniture_name', max_length=100, unique=True, verbose_name='家具名称')),
            ],
            options={
                'verbose_name': '家具',
                'verbose_name_plural': '家具',
                'db_table': 'furniture',
            },
        ),
    ]
