# Generated by Django 5.2.12 on 2026-04-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playtask', '0001_initial'),
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaytaskRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='关联ID')),
                ('playtask_progress', models.IntegerField(db_column='playtask_progress', default=0, verbose_name='任务进度')),
                ('playtask', models.ForeignKey(db_column='playtask_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='playtask.playtask', verbose_name='玩法任务')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='playtask_relations', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户玩法任务关联',
                'verbose_name_plural': '用户玩法任务关联',
                'db_table': 'user_playtask_relation',
                'constraints': [models.UniqueConstraint(fields=('user', 'playtask'), name='uniq_user_playtask')],
            },
        ),
    ]
