# Generated by Django 5.2.12 on 2026-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('user_profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='头像')),
                ('user_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('user_password', models.CharField(max_length=128, verbose_name='密码')),
                ('user_mail_address', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
