# Generated by Django 5.2.12 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mail_address',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
