# Generated by Django 5.2.12 on 2026-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_mail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
