# Generated by Django 5.2.12 on 2026-04-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='用户状态'),
        ),
    ]
