# Generated by Django 5.2.12 on 2026-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='用户角色'),
        ),
    ]
