# Generated by Django 5.2.12 on 2026-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetEyeUv',
            fields=[
                ('pet_eye_uv_id', models.CharField(db_column='pet_eye_uv_id', max_length=36, primary_key=True, serialize=False, verbose_name='眼球UV记录ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_image_path', models.CharField(default='', max_length=512, verbose_name='原图本地路径')),
                ('workflow_status', models.CharField(default='upload_success', max_length=32, verbose_name='工作流状态')),
                ('eye_count', models.IntegerField(default=0, verbose_name='检测到的眼睛数量')),
                ('eye_uv_url_0', models.CharField(default='', max_length=512, verbose_name='眼球0 UV贴图URL')),
                ('eye_uv_url_1', models.CharField(default='', max_length=512, verbose_name='眼球1 UV贴图URL')),
                ('base_bgr_0', models.CharField(default='', max_length=50, verbose_name='眼球0虹膜BGR')),
                ('base_bgr_1', models.CharField(default='', max_length=50, verbose_name='眼球1虹膜BGR')),
                ('workflow_error', models.TextField(blank=True, default='', verbose_name='工作流错误信息')),
            ],
            options={
                'verbose_name': '宠物眼球UV贴图记录',
                'verbose_name_plural': '宠物眼球UV贴图记录',
                'db_table': 'pet_eye_uv',
                'ordering': ['-created_at'],
            },
        ),
    ]
