# Generated by Django 5.2.12 on 2026-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playtask',
            fields=[
                ('playtask_id', models.AutoField(db_column='playtask_id', primary_key=True, serialize=False, verbose_name='玩法任务ID')),
                ('playtask_name', models.CharField(db_column='playtask_name', max_length=100, unique=True, verbose_name='玩法任务名称')),
            ],
            options={
                'verbose_name': '玩法任务',
                'verbose_name_plural': '玩法任务',
                'db_table': 'playtask',
            },
        ),
    ]
