# Generated by Django 5.2.12 on 2026-04-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_action', '0001_initial'),
        ('user_task', '0002_usertask_uniq_user_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskActionRelation',
            fields=[
                ('relation_id', models.AutoField(db_column='relation_id', primary_key=True, serialize=False, verbose_name='鍏宠仈ID')),
                ('pet_action', models.ForeignKey(db_column='pet_action_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_relations', to='pet_action.petaction', verbose_name='鍔ㄤ綔')),
                ('user_task', models.ForeignKey(db_column='user_task_id', on_delete=django.db.models.deletion.CASCADE, related_name='action_relations', to='user_task.usertask', verbose_name='浠诲姟')),
            ],
            options={
                'verbose_name': '浠诲姟鍔ㄤ綔鍏宠仈',
                'verbose_name_plural': '浠诲姟鍔ㄤ綔鍏宠仈',
                'db_table': 'user_task_action_relation',
                'unique_together': {('user_task', 'pet_action')},
            },
        ),
    ]
