# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/furniture.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/furniture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/proto/furniture.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"=\n\rFurnitureInfo\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66urniture_name\x18\x02 \x01(\t\"\xa4\x01\n\x11\x46urnitureResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.aipet.FurnitureInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"0\n\x16\x43reateFurnitureRequest\x12\x16\n\x0e\x66urniture_name\x18\x01 \x01(\t\"F\n\x16UpdateFurnitureRequest\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66urniture_name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.furniture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FURNITUREINFO']._serialized_start=60
  _globals['_FURNITUREINFO']._serialized_end=121
  _globals['_FURNITURERESPONSE']._serialized_start=124
  _globals['_FURNITURERESPONSE']._serialized_end=288
  _globals['_CREATEFURNITUREREQUEST']._serialized_start=290
  _globals['_CREATEFURNITUREREQUEST']._serialized_end=338
  _globals['_UPDATEFURNITUREREQUEST']._serialized_start=340
  _globals['_UPDATEFURNITUREREQUEST']._serialized_end=410
# @@protoc_insertion_point(module_scope)
