# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_furniture_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_furniture_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'app/proto/user_furniture_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"\x85\x01\n\x15\x46urnitureRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x66urniture_id\x18\x03 \x01(\x05\x12\x16\n\x0e\x66urniture_name\x18\x04 \x01(\t\x12\x18\n\x10\x66urniture_amount\x18\x05 \x01(\x05\"+\n\x13\x46urnitureUnbindInfo\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\x05\"\xb0\x01\n\x15\x42indFurnitureResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1c.aipet.FurnitureRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb0\x01\n\x17UnbindFurnitureResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12(\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1a.aipet.FurnitureUnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb8\x01\n\x1d\x46urnitureRelationListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12*\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1c.aipet.FurnitureRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\",\n\x14\x42indFurnitureRequest\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\x05\".\n\x16UnbindFurnitureRequest\x12\x14\n\x0c\x66urniture_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_furniture_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FURNITURERELATIONINFO']._serialized_start=75
  _globals['_FURNITURERELATIONINFO']._serialized_end=208
  _globals['_FURNITUREUNBINDINFO']._serialized_start=210
  _globals['_FURNITUREUNBINDINFO']._serialized_end=253
  _globals['_BINDFURNITURERESPONSE']._serialized_start=256
  _globals['_BINDFURNITURERESPONSE']._serialized_end=432
  _globals['_UNBINDFURNITURERESPONSE']._serialized_start=435
  _globals['_UNBINDFURNITURERESPONSE']._serialized_end=611
  _globals['_FURNITURERELATIONLISTRESPONSE']._serialized_start=614
  _globals['_FURNITURERELATIONLISTRESPONSE']._serialized_end=798
  _globals['_BINDFURNITUREREQUEST']._serialized_start=800
  _globals['_BINDFURNITUREREQUEST']._serialized_end=844
  _globals['_UNBINDFURNITUREREQUEST']._serialized_start=846
  _globals['_UNBINDFURNITUREREQUEST']._serialized_end=892
# @@protoc_insertion_point(module_scope)
