# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_playtask_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_playtask_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&app/proto/user_playtask_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"\x83\x01\n\x14PlaytaskRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x13\n\x0bplaytask_id\x18\x03 \x01(\x05\x12\x15\n\rplaytask_name\x18\x04 \x01(\t\x12\x19\n\x11playtask_progress\x18\x05 \x01(\x05\")\n\x12PlaytaskUnbindInfo\x12\x13\n\x0bplaytask_id\x18\x01 \x01(\x05\"\xae\x01\n\x14\x42indPlaytaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12)\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1b.aipet.PlaytaskRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xae\x01\n\x16UnbindPlaytaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.aipet.PlaytaskUnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb6\x01\n\x1cPlaytaskRelationListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12)\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1b.aipet.PlaytaskRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"*\n\x13\x42indPlaytaskRequest\x12\x13\n\x0bplaytask_id\x18\x01 \x01(\x05\",\n\x15UnbindPlaytaskRequest\x12\x13\n\x0bplaytask_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_playtask_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYTASKRELATIONINFO']._serialized_start=74
  _globals['_PLAYTASKRELATIONINFO']._serialized_end=205
  _globals['_PLAYTASKUNBINDINFO']._serialized_start=207
  _globals['_PLAYTASKUNBINDINFO']._serialized_end=248
  _globals['_BINDPLAYTASKRESPONSE']._serialized_start=251
  _globals['_BINDPLAYTASKRESPONSE']._serialized_end=425
  _globals['_UNBINDPLAYTASKRESPONSE']._serialized_start=428
  _globals['_UNBINDPLAYTASKRESPONSE']._serialized_end=602
  _globals['_PLAYTASKRELATIONLISTRESPONSE']._serialized_start=605
  _globals['_PLAYTASKRELATIONLISTRESPONSE']._serialized_end=787
  _globals['_BINDPLAYTASKREQUEST']._serialized_start=789
  _globals['_BINDPLAYTASKREQUEST']._serialized_end=831
  _globals['_UNBINDPLAYTASKREQUEST']._serialized_start=833
  _globals['_UNBINDPLAYTASKREQUEST']._serialized_end=877
# @@protoc_insertion_point(module_scope)
