# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_property_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_property_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&app/proto/user_property_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"\x81\x01\n\x14PropertyRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x13\n\x0bproperty_id\x18\x03 \x01(\x05\x12\x15\n\rproperty_name\x18\x04 \x01(\t\x12\x17\n\x0fproperty_amount\x18\x05 \x01(\x05\")\n\x12PropertyUnbindInfo\x12\x13\n\x0bproperty_id\x18\x01 \x01(\x05\"\xae\x01\n\x14\x42indPropertyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12)\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1b.aipet.PropertyRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xae\x01\n\x16UnbindPropertyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.aipet.PropertyUnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb6\x01\n\x1cPropertyRelationListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12)\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1b.aipet.PropertyRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"*\n\x13\x42indPropertyRequest\x12\x13\n\x0bproperty_id\x18\x01 \x01(\x05\",\n\x15UnbindPropertyRequest\x12\x13\n\x0bproperty_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_property_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPERTYRELATIONINFO']._serialized_start=74
  _globals['_PROPERTYRELATIONINFO']._serialized_end=203
  _globals['_PROPERTYUNBINDINFO']._serialized_start=205
  _globals['_PROPERTYUNBINDINFO']._serialized_end=246
  _globals['_BINDPROPERTYRESPONSE']._serialized_start=249
  _globals['_BINDPROPERTYRESPONSE']._serialized_end=423
  _globals['_UNBINDPROPERTYRESPONSE']._serialized_start=426
  _globals['_UNBINDPROPERTYRESPONSE']._serialized_end=600
  _globals['_PROPERTYRELATIONLISTRESPONSE']._serialized_start=603
  _globals['_PROPERTYRELATIONLISTRESPONSE']._serialized_end=785
  _globals['_BINDPROPERTYREQUEST']._serialized_start=787
  _globals['_BINDPROPERTYREQUEST']._serialized_end=829
  _globals['_UNBINDPROPERTYREQUEST']._serialized_start=831
  _globals['_UNBINDPROPERTYREQUEST']._serialized_end=875
# @@protoc_insertion_point(module_scope)
