# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_wealth_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_wealth_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$app/proto/user_wealth_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"y\n\x12WealthRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\twealth_id\x18\x03 \x01(\x05\x12\x13\n\x0bwealth_name\x18\x04 \x01(\t\x12\x15\n\rwealth_amount\x18\x05 \x01(\x05\"%\n\x10WealthUnbindInfo\x12\x11\n\twealth_id\x18\x01 \x01(\x05\"\xaa\x01\n\x12\x42indWealthResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.aipet.WealthRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xaa\x01\n\x14UnbindWealthResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.aipet.WealthUnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb2\x01\n\x1aWealthRelationListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\'\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x19.aipet.WealthRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"&\n\x11\x42indWealthRequest\x12\x11\n\twealth_id\x18\x01 \x01(\x05\"(\n\x13UnbindWealthRequest\x12\x11\n\twealth_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_wealth_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEALTHRELATIONINFO']._serialized_start=71
  _globals['_WEALTHRELATIONINFO']._serialized_end=192
  _globals['_WEALTHUNBINDINFO']._serialized_start=194
  _globals['_WEALTHUNBINDINFO']._serialized_end=231
  _globals['_BINDWEALTHRESPONSE']._serialized_start=234
  _globals['_BINDWEALTHRESPONSE']._serialized_end=404
  _globals['_UNBINDWEALTHRESPONSE']._serialized_start=407
  _globals['_UNBINDWEALTHRESPONSE']._serialized_end=577
  _globals['_WEALTHRELATIONLISTRESPONSE']._serialized_start=580
  _globals['_WEALTHRELATIONLISTRESPONSE']._serialized_end=758
  _globals['_BINDWEALTHREQUEST']._serialized_start=760
  _globals['_BINDWEALTHREQUEST']._serialized_end=798
  _globals['_UNBINDWEALTHREQUEST']._serialized_start=800
  _globals['_UNBINDWEALTHREQUEST']._serialized_end=840
# @@protoc_insertion_point(module_scope)
