# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pp/proto/user.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaa\x01\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x1c\n\x14user_profile_picture\x18\x03 \x01(\t\x12\x19\n\x11user_phone_number\x18\x04 \x01(\t\x12\x19\n\x11user_mail_address\x18\x05 \x01(\t\x12\x13\n\x0buser_status\x18\x06 \x01(\x05\x12\x11\n\tuser_role\x18\x07 \x01(\x05\"8\n\tTokenPair\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"K\n\tLoginData\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.aipet.UserInfo\x12\x1f\n\x05token\x18\x02 \x01(\x0b\x32\x10.aipet.TokenPair\"\x9a\x01\n\x0cUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1d\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0f.aipet.UserInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xa0\x01\n\x11UserLoginResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1e\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x10.aipet.LoginData\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"}\n\x11\x43reateUserRequest\x12\x19\n\x11user_phone_number\x18\x01 \x01(\t\x12\x15\n\ruser_password\x18\x02 \x01(\t\x12\x1d\n\x15user_password_confirm\x18\x03 \x01(\t\x12\x17\n\x0fuser_phone_code\x18\x04 \x01(\t\"m\n\x0cLoginRequest\x12\x19\n\x11user_phone_number\x18\x01 \x01(\t\x12\x12\n\nlogin_type\x18\x02 \x01(\t\x12\x15\n\ruser_password\x18\x03 \x01(\t\x12\x17\n\x0fuser_phone_code\x18\x04 \x01(\t\"&\n\x11UpdateUserRequest\x12\x11\n\tuser_name\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO']._serialized_start=86
  _globals['_USERINFO']._serialized_end=256
  _globals['_TOKENPAIR']._serialized_start=258
  _globals['_TOKENPAIR']._serialized_end=314
  _globals['_LOGINDATA']._serialized_start=316
  _globals['_LOGINDATA']._serialized_end=391
  _globals['_USERRESPONSE']._serialized_start=394
  _globals['_USERRESPONSE']._serialized_end=548
  _globals['_USERLOGINRESPONSE']._serialized_start=551
  _globals['_USERLOGINRESPONSE']._serialized_end=711
  _globals['_CREATEUSERREQUEST']._serialized_start=713
  _globals['_CREATEUSERREQUEST']._serialized_end=838
  _globals['_LOGINREQUEST']._serialized_start=840
  _globals['_LOGINREQUEST']._serialized_end=949
  _globals['_UPDATEUSERREQUEST']._serialized_start=951
  _globals['_UPDATEUSERREQUEST']._serialized_end=989
# @@protoc_insertion_point(module_scope)
