# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_task_action_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_task_action_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)app/proto/user_task_action_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"P\n\x0cRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x14\n\x0cuser_task_id\x18\x02 \x01(\x05\x12\x15\n\rpet_action_id\x18\x03 \x01(\x05\"9\n\nUnbindInfo\x12\x14\n\x0cuser_task_id\x18\x01 \x01(\x05\x12\x15\n\rpet_action_id\x18\x02 \x01(\x05\"A\n\x0f\x41\x63tionBriefInfo\x12\x15\n\rpet_action_id\x18\x01 \x01(\x05\x12\x17\n\x0fpet_action_name\x18\x02 \x01(\t\"\x9e\x01\n\x0c\x42indResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12!\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x13.aipet.RelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\x9e\x01\n\x0eUnbindResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1f\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x11.aipet.UnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xa7\x01\n\x12\x41\x63tionListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12$\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x16.aipet.ActionBriefInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"@\n\x11\x42indActionRequest\x12\x14\n\x0cuser_task_id\x18\x01 \x01(\x05\x12\x15\n\rpet_action_id\x18\x02 \x01(\x05\"B\n\x13UnbindActionRequest\x12\x14\n\x0cuser_task_id\x18\x01 \x01(\x05\x12\x15\n\rpet_action_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_task_action_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELATIONINFO']._serialized_start=76
  _globals['_RELATIONINFO']._serialized_end=156
  _globals['_UNBINDINFO']._serialized_start=158
  _globals['_UNBINDINFO']._serialized_end=215
  _globals['_ACTIONBRIEFINFO']._serialized_start=217
  _globals['_ACTIONBRIEFINFO']._serialized_end=282
  _globals['_BINDRESPONSE']._serialized_start=285
  _globals['_BINDRESPONSE']._serialized_end=443
  _globals['_UNBINDRESPONSE']._serialized_start=446
  _globals['_UNBINDRESPONSE']._serialized_end=604
  _globals['_ACTIONLISTRESPONSE']._serialized_start=607
  _globals['_ACTIONLISTRESPONSE']._serialized_end=774
  _globals['_BINDACTIONREQUEST']._serialized_start=776
  _globals['_BINDACTIONREQUEST']._serialized_end=840
  _globals['_UNBINDACTIONREQUEST']._serialized_start=842
  _globals['_UNBINDACTIONREQUEST']._serialized_end=908
# @@protoc_insertion_point(module_scope)
