# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/proto/user_task.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"H\n\x0cUserTaskInfo\x12\x14\n\x0cuser_task_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\ttask_name\x18\x03 \x01(\t\"\xa2\x01\n\x10UserTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12!\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x13.aipet.UserTaskInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xa6\x01\n\x14UserTaskListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12!\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x13.aipet.UserTaskInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"*\n\x15\x43reateUserTaskRequest\x12\x11\n\ttask_name\x18\x01 \x01(\t\"@\n\x15UpdateUserTaskRequest\x12\x14\n\x0cuser_task_id\x18\x01 \x01(\x05\x12\x11\n\ttask_name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERTASKINFO']._serialized_start=60
  _globals['_USERTASKINFO']._serialized_end=132
  _globals['_USERTASKRESPONSE']._serialized_start=135
  _globals['_USERTASKRESPONSE']._serialized_end=297
  _globals['_USERTASKLISTRESPONSE']._serialized_start=300
  _globals['_USERTASKLISTRESPONSE']._serialized_end=466
  _globals['_CREATEUSERTASKREQUEST']._serialized_start=468
  _globals['_CREATEUSERTASKREQUEST']._serialized_end=510
  _globals['_UPDATEUSERTASKREQUEST']._serialized_start=512
  _globals['_UPDATEUSERTASKREQUEST']._serialized_end=576
# @@protoc_insertion_point(module_scope)
