# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user_achievement_relation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/user_achievement_relation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)app/proto/user_achievement_relation.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"q\n\x17\x41\x63hievementRelationInfo\x12\x13\n\x0brelation_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x16\n\x0e\x61\x63hievement_id\x18\x03 \x01(\x05\x12\x18\n\x10\x61\x63hievement_name\x18\x04 \x01(\t\"/\n\x15\x41\x63hievementUnbindInfo\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\x05\"\xb4\x01\n\x17\x42indAchievementResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12,\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1e.aipet.AchievementRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xb4\x01\n\x19UnbindAchievementResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12*\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1c.aipet.AchievementUnbindInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"\xbc\x01\n\x1f\x41\x63hievementRelationListResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12,\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x1e.aipet.AchievementRelationInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"0\n\x16\x42indAchievementRequest\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\x05\"2\n\x18UnbindAchievementRequest\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user_achievement_relation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACHIEVEMENTRELATIONINFO']._serialized_start=76
  _globals['_ACHIEVEMENTRELATIONINFO']._serialized_end=189
  _globals['_ACHIEVEMENTUNBINDINFO']._serialized_start=191
  _globals['_ACHIEVEMENTUNBINDINFO']._serialized_end=238
  _globals['_BINDACHIEVEMENTRESPONSE']._serialized_start=241
  _globals['_BINDACHIEVEMENTRESPONSE']._serialized_end=421
  _globals['_UNBINDACHIEVEMENTRESPONSE']._serialized_start=424
  _globals['_UNBINDACHIEVEMENTRESPONSE']._serialized_end=604
  _globals['_ACHIEVEMENTRELATIONLISTRESPONSE']._serialized_start=607
  _globals['_ACHIEVEMENTRELATIONLISTRESPONSE']._serialized_end=795
  _globals['_BINDACHIEVEMENTREQUEST']._serialized_start=797
  _globals['_BINDACHIEVEMENTREQUEST']._serialized_end=845
  _globals['_UNBINDACHIEVEMENTREQUEST']._serialized_start=847
  _globals['_UNBINDACHIEVEMENTREQUEST']._serialized_end=897
# @@protoc_insertion_point(module_scope)
