# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/wealth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/proto/wealth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto import common_pb2 as app_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/proto/wealth.proto\x12\x05\x61ipet\x1a\x16\x61pp/proto/common.proto\"4\n\nWealthInfo\x12\x11\n\twealth_id\x18\x01 \x01(\x05\x12\x13\n\x0bwealth_name\x18\x02 \x01(\t\"\x9e\x01\n\x0eWealthResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1f\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x11.aipet.WealthInfo\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x12\'\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x16.aipet.ValidationErrorH\x00\x42\x11\n\x0fmessage_content\"*\n\x13\x43reateWealthRequest\x12\x13\n\x0bwealth_name\x18\x01 \x01(\t\"=\n\x13UpdateWealthRequest\x12\x11\n\twealth_id\x18\x01 \x01(\x05\x12\x13\n\x0bwealth_name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.wealth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEALTHINFO']._serialized_start=57
  _globals['_WEALTHINFO']._serialized_end=109
  _globals['_WEALTHRESPONSE']._serialized_start=112
  _globals['_WEALTHRESPONSE']._serialized_end=270
  _globals['_CREATEWEALTHREQUEST']._serialized_start=272
  _globals['_CREATEWEALTHREQUEST']._serialized_end=314
  _globals['_UPDATEWEALTHREQUEST']._serialized_start=316
  _globals['_UPDATEWEALTHREQUEST']._serialized_end=377
# @@protoc_insertion_point(module_scope)
